### PR TITLE
Support negated options for HAProxy transformer

### PR DESCRIPTION
**Pull request by andyshinn**
Allows options to be set `false` which will prefix them with `no`.

### CODE REVIEW

**Comment by progrium** [comment]
Previously, you could set a keyword value to `false` and it would drop the line. For example, if `daemon` is set to `true`, and you set it to `false` ... it would just remove the `daemon` keyword. Does the `no` prefix have the same effect? For example, can you have `no daemon` and it will work as you'd expect?

**Comment by andyshinn** [comment]
No, they both work differently. I wonder if it makes sense to support false
(no) and null (empty)? A special case could be made for options, too.

**Comment by progrium** [comment]
Is `no` just for the `options` keyword? If so, yeah, I'd special case it for `options`.

**Comment by andyshinn** [comment]
After skimming the docs, it does appear to be only for the `option` keyword.

**Comment by progrium** [comment]
Do you want to try to change the code to do this only for `option`?

**Comment by andyshinn** [comment]
Yea, I'll try my hand at that in the next couple days. Lets leave this open for now.

**Pull request closed without merging**
